// GENERATED by scripts/mirror-install.mjs from a capture. Owners may edit MIRROR_PAGES and the HTML files for routine site changes.
// Re-run the installer only to replace the captured site or its asset set. Empty on a redesign site.
import type { MirrorPage } from "@/lib/mirror/head";

export const MIRROR_PAGES: MirrorPage[] = [];

export const MIRROR_PATHS = new Set(MIRROR_PAGES.map((p) => p.path));

/** Origins of iframes the mirrored pages embed; next.config.ts grants them in frame-src. */
export const MIRROR_FRAME_SRC: string[] = [];

/** The original's own permanent redirects (old slugs its CMS still honoured); next.config.ts spreads them. */
export const MIRROR_REDIRECTS: { source: string; destination: string }[] = [];
